apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: financial
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - oracledatabase-financial.org
      secretName: oracledatabase-financial-tls
  rules:
    - host: oracledatabase-financial.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-springboot
                port:
                  number: 8090