ojdbc.agentmemory.database.url=jdbc:oracle:thin:@localhost:1521/freepdb1
ojdbc.agentmemory.database.user=scott
ojdbc.agentmemory.database.password=tiger

ojdbc.agentmemory.pool.enabled=true
ojdbc.agentmemory.pool.name=OAMJ_EXAMPLE_POOL
ojdbc.agentmemory.pool.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
ojdbc.agentmemory.pool.initial-size=1
ojdbc.agentmemory.pool.min-size=1
ojdbc.agentmemory.pool.max-size=5

ojdbc.agentmemory.schema.auto-create=true
ojdbc.agentmemory.schema.table-prefix=OAMJ_

ojdbc.agentmemory.embedding.provider=database
ojdbc.agentmemory.embedding.model=allminilm

ojdbc.agentmemory.llm.provider=ollama
ojdbc.agentmemory.llm.base-url=http://localhost:11434
ojdbc.agentmemory.llm.model=llama3.2:latest
ojdbc.agentmemory.llm.temperature=0.0

ojdbc.agentmemory.memory.extract-memories=true
