const express = require('express');
const mongoose = require('mongoose');
const bodyParser = require('body-parser');
const cors = require('cors');
const fetch = require('node-fetch');

// Initialize Express app
const app = express();
const PORT = process.env.PORT || 5001; // Changed from 5000 to 5001 to avoid AirPlay conflict

// Middleware
app.use(bodyParser.json());
app.use(cors());

// MongoDB connection (using Oracle JSON Duality View as MongoDB API)
const MONGO_URI = process.env.MONGO_URI || 'mongodb://financial:Welcome12345@IJ1TYZIR3WPWLPE-FINANCIALDB.adb.eu-frankfurt-1.oraclecloudapps.com:27017/financial?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true';
mongoose
  .connect(MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => console.log('Connected to Oracle JSON Duality View via MongoDB API'))
  .catch((err) => console.error('Error connecting to MongoDB API:', err));

// Define the schema (matches the JSON Duality View structure)
const accountSchema = new mongoose.Schema({
  _id: { type: String }, // Auto-generated by MongoDB or backend logic
  accountName: { type: String, required: true },
  accountType: { type: String, required: true },
  customerId: { type: String, required: true },
  accountOpenedDate: { type: Date, required: true },
  accountOtherDetails: { type: String },
  accountBalance: { type: Number, required: true },
});

// Create the model
const Account = mongoose.model('accounts_dv', accountSchema);

// Root endpoint to verify server is running
app.get('/', (req, res) => {
  res.json({
    message: 'MERN Stack Backend API is running!',
    status: 'OK',
    timestamp: new Date().toISOString(),
    endpoints: {
      'GET /': 'This status endpoint',
      'GET /api/accounts': 'Get all accounts',
      'POST /api/accounts': 'Create new account',
      'GET /api/accounts/:id': 'Get account by ID',
      'PUT /api/accounts/:id': 'Update account by ID',
      'DELETE /api/accounts/:id': 'Delete account by ID',
      'POST /accounts/api/accounts': 'Proxy endpoint for account creation'
    },
    database: {
      type: 'Oracle Database via MongoDB API',
      collection: 'accounts_dv',
      connection: MONGO_URI ? 'Environment variable configured' : 'Using fallback configuration'
    }
  });
});

// CRUD Endpoints

// Create an account
app.post(['/api/accounts', '/mern-backend/api/accounts'], async (req, res) => {
  try {
    const account = new Account(req.body);
    await account.save();
    res.status(201).json(account);
  } catch (err) {
    console.error('Error creating account:', err);
    res.status(500).json({ error: 'Failed to create account' });
  }
});

// Read all accounts
app.get(['/api/accounts', '/mern-backend/api/accounts'], async (req, res) => {
  try {
    const accounts = await Account.find({});
    res.json(accounts);
  } catch (err) {
    console.error('Error fetching accounts:', err);
    res.status(500).json({ error: 'Failed to fetch accounts' });
  }
});

// Read a single account by ID
app.get(['/api/accounts/:id', '/mern-backend/api/accounts/:id'], async (req, res) => {
  try {
    const account = await Account.findById(req.params.id);
    if (!account) {
      return res.status(404).json({ error: 'Account not found' });
    }
    res.json(account);
  } catch (err) {
    console.error('Error fetching account:', err);
    res.status(500).json({ error: 'Failed to fetch account' });
  }
});

// Update an account by ID
app.put(['/api/accounts/:id', '/mern-backend/api/accounts/:id'], async (req, res) => {
  try {
    const account = await Account.findByIdAndUpdate(req.params.id, req.body, {
      new: true,
      runValidators: true,
    });
    if (!account) {
      return res.status(404).json({ error: 'Account not found' });
    }
    res.json(account);
  } catch (err) {
    console.error('Error updating account:', err);
    res.status(500).json({ error: 'Failed to update account' });
  }
});

// Delete an account by ID
app.delete(['/api/accounts/:id', '/mern-backend/api/accounts/:id'], async (req, res) => {
  try {
    const account = await Account.findByIdAndDelete(req.params.id);
    if (!account) {
      return res.status(404).json({ error: 'Account not found' });
    }
    res.json({ message: 'Account deleted successfully' });
  } catch (err) {
    console.error('Error deleting account:', err);
    res.status(500).json({ error: 'Failed to delete account' });
  }
});

// Proxy endpoint to create an account using a dynamic backend URL
app.post('/accounts/api/accounts', async (req, res) => {
  const { url, accountData } = req.body;
  if (!url || !accountData) {
    return res.status(400).json({ error: 'Missing url or accountData in request body' });
  }

  try {
    const backendRes = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(accountData),
    });

    const data = await backendRes.json();
    res.status(backendRes.status).json(data);
  } catch (err) {
    console.error('Error forwarding account creation:', err);
    res.status(500).json({ error: 'Failed to create account via backend' });
  }
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});