apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      volumes:
        - name: creds
          secret:
            secretName: financialdb-wallet-secret
            defaultMode: 420
      containers:
        - name: mern-backend
          image: eu-frankfurt-1.ocir.io/oradbclouducm/financial/mern-backend:0.1.1747795524
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              value: financial
            - name: DB_URL
              value: jdbc:oracle:thin:@financialdb_high?TNS_ADMIN=/oraclefinancial/creds
            - name: DB_PASSWORD
              value: Welcome12345
            - name: spring.datasource.username
              value: financial
            - name: spring.datasource.url
              value: jdbc:oracle:thin:@financialdb_high?TNS_ADMIN=/oraclefinancial/creds
            - name: spring.datasource.password
              value: Welcome12345
          resources: {}
          volumeMounts:
            - name: creds
              mountPath: /oraclefinancial/creds
      restartPolicy: Always
#      imagePullSecrets:
#        - name: regcred
#      schedulerName: default-scheduler