CREATE PROPERTY GRAPH "bank_graph"
  VERTEX TABLES (
    "FINANCIAL"."ACCOUNTS"
      KEY ( "ACCOUNT_ID" )
      PROPERTIES ( "ACCOUNT_BALANCE", "ACCOUNT_ID", "ACCOUNT_NAME", "ACCOUNT_OPENED_DATE", "ACCOUNT_OTHER_DETAILS", "ACCOUNT_TYPE", "CUSTOMER_ID" )
  )
  EDGE TABLES (
    "FINANCIAL"."TRANSFERS" KEY ( "TXN_ID" )
      SOURCE KEY ( "SRC_ACCT_ID" ) REFERENCES "ACCOUNTS"( "ACCOUNT_ID" )
      DESTINATION KEY ( "DST_ACCT_ID" ) REFERENCES "ACCOUNTS"( "ACCOUNT_ID" )
      PROPERTIES ( "AMOUNT", "DESCRIPTION", "DST_ACCT_ID", "SRC_ACCT_ID", "TXN_ID" )
  )