-- Optional smoke-test setup for the existing financial Autonomous Database.
-- Run as the FINANCIAL user. This creates a small regular Oracle table so the
-- Spring Boot lakehouse app can be tested before an Iceberg-backed SQL object
-- is available.

whenever sqlerror exit sql.sqlcode

drop table if exists lakehouse_jdbc_smoke_test purge;

create table lakehouse_jdbc_smoke_test (
  transaction_id number generated by default as identity primary key,
  account_id number not null,
  transaction_ts timestamp default systimestamp not null,
  channel varchar2(30) not null,
  amount number(12,2) not null,
  risk_score number(5) not null,
  notes varchar2(200)
);

insert into lakehouse_jdbc_smoke_test (account_id, channel, amount, risk_score, notes)
values (101, 'CARD', 42.35, 12, 'baseline card purchase');

insert into lakehouse_jdbc_smoke_test (account_id, channel, amount, risk_score, notes)
values (101, 'WIRE', 2840.00, 78, 'larger outgoing wire');

insert into lakehouse_jdbc_smoke_test (account_id, channel, amount, risk_score, notes)
values (205, 'ACH', 316.75, 33, 'standard ACH payment');

commit;

prompt Created LAKEHOUSE_JDBC_SMOKE_TEST for JDBC smoke testing.
