apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - react-frontend.yaml
  - springboot-backend.yaml
  - microtx-account.yaml
  - microtx-transfer.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: financial-demo
    includeSelectors: true
