steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.mcp-app-cloud-run
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
