apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclejavaai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oraclejavaai
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oraclejavaai
    spec:
      volumes:
        - name: creds
          secret:
            secretName: ragdb-wallet-secret
            defaultMode: 420
      containers:
        - name: oraclejavaai
          image: us-ashburn-1.ocir.io/oradbclouducm/podsofkon/podsofkon:sustainableai
#          image: us-ashburn-1.ocir.io/oradbclouducm/oraclejavaai/oraclejavaai:0.2
#          image: us-ashburn-1.ocir.io/oradbclouducm/gd74087885/xr-admin:0.1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: DEBUG
            - name: server_port
              value: '8080'
            - name: spring.datasource.username
              value: admin
            - name: spring.datasource.url
              value: jdbc:oracle:thin:@ragdb_tp?TNS_ADMIN=/oraclejavaai/creds
            - name: spring.datasource.password
              value: Welcome123456
          resources: {}
          volumeMounts:
            - name: creds
              mountPath: /oraclejavaai/creds
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
