apiVersion: v1
kind: Service
metadata:
  name: oraclejavaai
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # nodePort: 32462
  selector:
    app: oraclejavaai
  type: LoadBalancer
