spring:
  main:
    allow-circular-references: true
  security:
    user:
      name: oracleai
      password: oracleai

  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    cors:
      allowed-origin-patterns: ["*"]  # ✅ Allow all origins
      allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed-headers: ["*"]

  servlet:
    websocket:
      buffer-size: 65536  # ✅ Increase WebSocket buffer size
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

  cloud:
    oci:
      config:
        type: INSTANCE_PRINCIPAL

#  datasource:
#    url: jdbc:oracle:thin:@selectaidb_high?TNS_ADMIN=C:/Users/opc/Downloads/Wallet_SelectAIDB/Wallet_SelectAIDB
#
#    username: moviestream
#    password: Welcome12345
#    driver-class-name: oracle.jdbc.OracleDriver
#    type: oracle.ucp.jdbc.PoolDataSource
#    oracleucp:
#      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
#      connection-pool-name: AccountConnectionPool
#      initial-pool-size: 15s
#      min-pool-size: 10
#      max-pool-size: 30
#  ai:
#    vectorstore:
#      oracle:
#        index-type: IVF
#        distance-type: COSINE
#        dimensions: 1536

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.web.cors: DEBUG
#    org.springframework.web.socket: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
#  port: 8080
#  port: 8444
  port: 443
  tomcat:
    max-swallow-size: 200MB
  ssl:
    enabled: true
    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
    key-store: classpath:aiholoorg.p12
    key-store-password: Welcome1
#    key-alias: springboot
    key-alias: aiholoorg
