#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FINANCIAL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  source "${ENV_FILE}"
  set +a
fi

CONTAINER_CLI="${CONTAINER_CLI:-podman}"
TAG="${TAG:-$(date +%Y%m%d%H%M%S)}"
DOCKER_REGISTRY="${DOCKER_REGISTRY:?Set DOCKER_REGISTRY, for example fra.ocir.io/<namespace>/financial}"
PUSH_IMAGES="${PUSH_IMAGES:-true}"
PUBLIC_HOSTNAME="${PUBLIC_HOSTNAME:-oracledev.ai}"
APP_BASE_PATH="${APP_BASE_PATH:-/financial}"
API_BASE_PATH="${API_BASE_PATH:-${APP_BASE_PATH}/api}"
ACCOUNTS_API_BASE_PATH="${ACCOUNTS_API_BASE_PATH:-${APP_BASE_PATH}/accounts-api}"
TRANSFER_API_BASE_PATH="${TRANSFER_API_BASE_PATH:-${APP_BASE_PATH}/transfer-api}"
MERN_BACKEND_BASE_PATH="${MERN_BACKEND_BASE_PATH:-${APP_BASE_PATH}/mern-backend}"
PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-https://${PUBLIC_HOSTNAME}}"
PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-${PUBLIC_ORIGIN}${APP_BASE_PATH}}"

REACT_FRONTEND_IMAGE_NAME="${REACT_FRONTEND_IMAGE_NAME:-react-frontend}"
SPRINGBOOT_BACKEND_IMAGE_NAME="${SPRINGBOOT_BACKEND_IMAGE_NAME:-springboot-backend}"
MICROTX_ACCOUNT_IMAGE_NAME="${MICROTX_ACCOUNT_IMAGE_NAME:-microtx-account}"
MICROTX_TRANSFER_IMAGE_NAME="${MICROTX_TRANSFER_IMAGE_NAME:-microtx-transfer}"

build_and_push() {
  local context_dir="$1"
  local image_name="$2"
  shift 2
  local image="${DOCKER_REGISTRY}/${image_name}:${TAG}"

  echo "==> Building ${image}"
  "${CONTAINER_CLI}" buildx build --platform linux/amd64 "$@" -t "${image}" "${context_dir}"

  if [[ "${PUSH_IMAGES}" == "true" ]]; then
    echo "==> Pushing ${image}"
    "${CONTAINER_CLI}" push --format docker "${image}"
  else
    echo "==> Skipping push for ${image} because PUSH_IMAGES=false"
  fi
}

build_and_push "${FINANCIAL_DIR}/react-frontend" "${REACT_FRONTEND_IMAGE_NAME}" \
  --build-arg "PUBLIC_URL=${PUBLIC_URL:-${APP_BASE_PATH}}" \
  --build-arg "REACT_APP_BASE_PATH=${REACT_APP_BASE_PATH:-${APP_BASE_PATH}}" \
  --build-arg "REACT_APP_API_BASE_PATH=${REACT_APP_API_BASE_PATH:-${API_BASE_PATH}}" \
  --build-arg "REACT_APP_PUBLIC_BASE_URL=${REACT_APP_PUBLIC_BASE_URL:-${PUBLIC_BASE_URL}}" \
  --build-arg "REACT_APP_MICROTX_ACCOUNT_SERVICE_URL=${REACT_APP_MICROTX_ACCOUNT_SERVICE_URL:-${ACCOUNTS_API_BASE_PATH}}" \
  --build-arg "REACT_APP_MICROTX_TRANSFER_SERVICE_URL=${REACT_APP_MICROTX_TRANSFER_SERVICE_URL:-${TRANSFER_API_BASE_PATH}}" \
  --build-arg "REACT_APP_MERN_SQL_ORACLE_SERVICE_URL=${REACT_APP_MERN_SQL_ORACLE_SERVICE_URL:-${ACCOUNTS_API_BASE_PATH}}" \
  --build-arg "REACT_APP_MERN_MONGODB_JSONDUALITY_ORACLE_SERVICE_URL=${REACT_APP_MERN_MONGODB_JSONDUALITY_ORACLE_SERVICE_URL:-${MERN_BACKEND_BASE_PATH}}" \
  --build-arg "REACT_APP_MERN_BACKEND_SERVICE_URL=${REACT_APP_MERN_BACKEND_SERVICE_URL:-${MERN_BACKEND_BASE_PATH}}" \
  --build-arg "REACT_APP_MERN_MONGODB_SERVICE_URL=${REACT_APP_MERN_MONGODB_SERVICE_URL:-${ACCOUNTS_API_BASE_PATH}}" \
  --build-arg "REACT_APP_AI_AGENTS_BACKEND_URL=${REACT_APP_AI_AGENTS_BACKEND_URL:-${APP_BASE_PATH}/aiagent}" \
  --build-arg "REACT_APP_ORDS_BASE_URL=${REACT_APP_ORDS_BASE_URL:-}" \
  --build-arg "REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-${API_BASE_PATH}}" \
  --build-arg "REACT_APP_JAVA_ACCOUNTDETAIL_SERVICE_URL=${REACT_APP_JAVA_ACCOUNTDETAIL_SERVICE_URL:-${ACCOUNTS_API_BASE_PATH}}" \
  --build-arg "REACT_APP_GRAPH_LAUNDERING_SERVICE_URL=${REACT_APP_GRAPH_LAUNDERING_SERVICE_URL:-${API_BASE_PATH}}" \
  --build-arg "REACT_APP_TRUECACHE_STOCK_SERVICE_URL=${REACT_APP_TRUECACHE_STOCK_SERVICE_URL:-${API_BASE_PATH}/truecache}" \
  --build-arg "REACT_APP_SHARDING_SPATIAL_CC_SERVICE_URL=${REACT_APP_SHARDING_SPATIAL_CC_SERVICE_URL:-${API_BASE_PATH}}" \
  --build-arg "REACT_APP_STOCK_SERVICE_URL=${REACT_APP_STOCK_SERVICE_URL:-${API_BASE_PATH}}" \
  --build-arg "REACT_APP_KAFKA_TXEVENTQ_SERVICE_URL=${REACT_APP_KAFKA_TXEVENTQ_SERVICE_URL:-${API_BASE_PATH}/kafka}" \
  --build-arg "REACT_APP_AIAGENT_VECTOR_ADVISOR_SERVICE_URL=${REACT_APP_AIAGENT_VECTOR_ADVISOR_SERVICE_URL:-${APP_BASE_PATH}/aiagent}" \
  --build-arg "REACT_APP_SPEECH_SELECTAI_QUERY_SERVICE_URL=${REACT_APP_SPEECH_SELECTAI_QUERY_SERVICE_URL:-${APP_BASE_PATH}/selectai}" \
  --build-arg "REACT_APP_GRAFANA_URL=${REACT_APP_GRAFANA_URL:-${APP_BASE_PATH}/grafana}"

build_and_push "${FINANCIAL_DIR}/springboot-backend" "${SPRINGBOOT_BACKEND_IMAGE_NAME}"
build_and_push "${FINANCIAL_DIR}/microtx-saga-lockless-bank-transfer/account" "${MICROTX_ACCOUNT_IMAGE_NAME}"
build_and_push "${FINANCIAL_DIR}/microtx-saga-lockless-bank-transfer/transfer" "${MICROTX_TRANSFER_IMAGE_NAME}"

cat <<EOF

Built images:
  ${DOCKER_REGISTRY}/${REACT_FRONTEND_IMAGE_NAME}:${TAG}
  ${DOCKER_REGISTRY}/${SPRINGBOOT_BACKEND_IMAGE_NAME}:${TAG}
  ${DOCKER_REGISTRY}/${MICROTX_ACCOUNT_IMAGE_NAME}:${TAG}
  ${DOCKER_REGISTRY}/${MICROTX_TRANSFER_IMAGE_NAME}:${TAG}

Keep TAG=${TAG} in ${ENV_FILE} before running deploy.sh.
EOF
