#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"
OCIR_USERNAME_OVERRIDE="${OCIR_USERNAME:-}"
OCIR_AUTH_TOKEN_OVERRIDE="${OCIR_AUTH_TOKEN:-}"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  source "${ENV_FILE}"
  set +a
fi

if [[ -n "${OCIR_USERNAME_OVERRIDE}" ]]; then
  OCIR_USERNAME="${OCIR_USERNAME_OVERRIDE}"
fi

if [[ -n "${OCIR_AUTH_TOKEN_OVERRIDE}" ]]; then
  OCIR_AUTH_TOKEN="${OCIR_AUTH_TOKEN_OVERRIDE}"
fi

CONTAINER_CLI="${CONTAINER_CLI:-podman}"
OCIR_REGISTRY="${OCIR_REGISTRY:-${DOCKER_REGISTRY%%/*}}"
OCIR_IDENTITY_DOMAIN="${OCIR_IDENTITY_DOMAIN:-}"

if [[ -z "${OCIR_USERNAME:-}" ]]; then
  : "${OCIR_TENANCY_NAMESPACE:?Set OCIR_TENANCY_NAMESPACE or OCIR_USERNAME}"
  : "${OCI_USERNAME:?Set OCI_USERNAME or OCIR_USERNAME}"
  if [[ -n "${OCIR_IDENTITY_DOMAIN}" ]]; then
    OCIR_USERNAME="${OCIR_TENANCY_NAMESPACE}/${OCIR_IDENTITY_DOMAIN}/${OCI_USERNAME}"
  else
    OCIR_USERNAME="${OCIR_TENANCY_NAMESPACE}/${OCI_USERNAME}"
  fi
fi

: "${OCIR_AUTH_TOKEN:?Set OCIR_AUTH_TOKEN in ${ENV_FILE}}"

printf '%s' "${OCIR_AUTH_TOKEN}" | "${CONTAINER_CLI}" login "${OCIR_REGISTRY}" \
  --username "${OCIR_USERNAME}" \
  --password-stdin

"${CONTAINER_CLI}" login --get-login "${OCIR_REGISTRY}"
