apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: springboot
    spec:
      containers:
        - name: frontend
          image: us-ashburn-1.ocir.io/oradbclouducm/financial/frontend:0.1
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: server_port
              value: "8080"
            - name: db_user
              value: "inventoryuser"
            - name: spring.datasource.username
              value: "inventoryuser"
            - name: db_url
              value: "jdbc:oracle:thin:@${frontend_DB_ALIAS}?TNS_ADMIN=/msdataworkshop/creds"
            - name: spring.datasource.url
              value: "jdbc:oracle:thin:@${frontend_DB_ALIAS}?TNS_ADMIN=/msdataworkshop/creds"
            - name: db_queueOwner
              value: "AQ"
            - name: db_orderQueueName
              value: "orderqueue"
            - name: db_frontendQueueName
              value: "frontendqueue"
            - name: OCI_REGION
              value: "${OCI_REGION-}"
            - name: VAULT_SECRET_OCID
              value: "${VAULT_SECRET_OCID-}"
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
                  optional: true #not needed/used if using VAULT_SECRET_OCID exists
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
                  optional: true #not needed/used if using VAULT_SECRET_OCID exists
          volumeMounts:
            - name: creds
              mountPath: /msdataworkshop/creds
          ports:
            - containerPort: 8080
      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: frontend-db-tns-admin-secret
