apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        version: springboot
    spec:
      containers:
      - name: inventory
        image: ${DOCKER_REGISTRY}/inventory-springboot:0.1
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: server_port
          value: "8080"
        - name: db_user
          value: "inventoryuser"
        - name: spring.datasource.username
          value: "inventoryuser"
        - name: db_url
          value: "jdbc:oracle:thin:@${INVENTORY_DB_ALIAS}?TNS_ADMIN=/msdataworkshop/creds"
        - name: spring.datasource.url
          value: "jdbc:oracle:thin:@${INVENTORY_DB_ALIAS}?TNS_ADMIN=/msdataworkshop/creds"
        - name: db_queueOwner
          value: "AQ"
        - name: db_orderQueueName
          value: "orderqueue"
        - name: db_inventoryQueueName
          value: "inventoryqueue"
        - name: OCI_REGION
          value: "${OCI_REGION-}"
        - name: VAULT_SECRET_OCID
          value: "${VAULT_SECRET_OCID-}"
        - name: db_password
          value: Welcome123456
        - name: spring.datasource.password
          value: Welcome123456
        volumeMounts:
        - name: creds
          mountPath: /msdataworkshop/creds
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: creds
        secret:
          secretName: lemmingdb-tns-admin




            - name: tns-admin
              secret:
                defaultMode: 420
                secretName: lemmingdb-tns-admin


apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2025-04-15T23:16:55Z"
  generation: 3
  labels:
    app.kubernetes.io/managed-by: obaas
    k8slens-edit-resource-version: v1
  name: account
  namespace: application
  resourceVersion: "2008120"
  uid: c7d2fb81-168b-460d-a519-ec3865c98780
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: account
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account
        version: 0.0.1
    spec:
      containers:
        - env:
            - name: app.container.port
              value: "8080"
            - name: spring.profiles.active
              value: default
            - name: spring.config.label
              value: 0.0.1
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: eureka.instance.hostname
              value: account.application
            - name: MP_LRA_COORDINATOR_URL
              value: http://otmm-tcs.otmm.svc.cluster.local:9000/api/v1/lra-coordinator
            - name: MP_LRA_PARTICIPANT_URL
              value: http://account.application.svc.cluster.local:8080
            - name: eureka.client.register-with-eureka
              value: "true"
            - name: eureka.client.fetch-registry
              value: "true"
            - name: eureka.client.service-url.defaultZone
              value: http://eureka.eureka:8761/eureka
            - name: zipkin.base-url
              value: http://jaegertracing-collector.observability.svc.cluster.local:9411/api/v2/spans
            - name: otel.exporter.otlp.endpoint
              value: http://open-telemetry-opentelemetry-collector.open-telemetry:4318/v1/traces
            - name: config.server.url
              value: http://config-server.config-server.svc.cluster.local:8080
            - name: spring.datasource.username
              value: account2
            - name: spring.datasource.password
              value: Welcome123456
            - name: DB_SERVICE
              valueFrom:
                secretKeyRef:
                  key: db.service
                  name: account-db-secrets
            - name: spring.datasource.url
              value: jdbc:oracle:thin:@$(DB_SERVICE)?TNS_ADMIN=/oracle/tnsadmin
            - name: CONNECT_STRING
              value: jdbc:oracle:thin:@$(DB_SERVICE)?TNS_ADMIN=/oracle/tnsadmin
          image: fra.ocir.io/oradbclouducm/lemming/application-account:0.0.1
          imagePullPolicy: Always
          name: account
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /oracle/tnsadmin
              name: tns-admin
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-auth
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tns-admin
          secret:
            defaultMode: 420
            secretName: lemmingdb-tns-admin
status:
  conditions:
    - lastTransitionTime: "2025-04-15T23:16:55Z"
      lastUpdateTime: "2025-04-16T00:03:24Z"
      message: ReplicaSet "account-7b7b54dbc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-04-19T01:40:50Z"
      lastUpdateTime: "2025-04-19T01:40:50Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
  observedGeneration: 3
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1