drop view if exists conversation_dv;
drop table if exists interlocutor;
drop table if exists conversation;

CREATE TABLE IF NOT EXISTS conversation
  (conversation_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   name    VARCHAR2(255) NOT NULL UNIQUE,
   CONSTRAINT conversation_pk PRIMARY KEY(conversation_id));

CREATE TABLE IF NOT EXISTS interlocutor
  (interlocutor_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   name      VARCHAR2(255) NOT NULL UNIQUE,
   dialogue      VARCHAR2(255) ,
   conversation_id   INTEGER,
   CONSTRAINT interlocutor_pk PRIMARY KEY(interlocutor_id),
   CONSTRAINT interlocutor_fk FOREIGN KEY(conversation_id) REFERENCES conversation(conversation_id));
   
CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW conversation_dv AS
  SELECT JSON {'conversationId'  IS t.conversation_id,
               'name'    IS t.name,
               'interlocutor'  IS
                 [ SELECT JSON {'interlocutorId' IS d.interlocutor_id,
                                'name'     IS d.name,
                                'dialogue'   IS d.dialogue WITH NOCHECK}
                     FROM interlocutor d WITH INSERT UPDATE
                     WHERE d.conversation_id = t.conversation_id ]}
    FROM conversation t WITH INSERT UPDATE DELETE;
