--run as aiuser

CREATE TABLE aivision_results
    (id RAW (16) NOT NULL,
     date_loaded TIMESTAMP WITH TIME ZONE,
     label varchar2(20),
     jsondata CLOB
     CONSTRAINT ensure_aivision_results_json CHECK (jsondata IS JSON));
create index aivisionresultsindex on aivision_results(jsondata) indextype is ctxsys.context;
select index_name, index_type, status from user_indexes where index_name = 'AIVISIONAIRESULTSINDEX';
select idx_name, idx_table, idx_text_name from ctx_user_indexes;
select token_text from dr$aivisionresultsindex$i;


CREATE TABLE aispeech_results
    (id RAW (16) NOT NULL,
     date_loaded TIMESTAMP WITH TIME ZONE,
     label varchar2(20),
     jsondata CLOB
     CONSTRAINT aispeech_results_json CHECK (jsondata IS JSON));
create index aispeechresultsindex on aispeech_results(jsondata) indextype is ctxsys.context;
select index_name, index_type, status from user_indexes where index_name = 'AISPEECHRESULTSINDEX';
select idx_name, idx_table, idx_text_name from ctx_user_indexes;
select token_text from dr$aispeechresultsindex$i;

CREATE OR REPLACE FUNCTION execute_dynamic_sql(p_sql IN VARCHAR2) RETURN VARCHAR2 IS
    v_result VARCHAR2(4000);
BEGIN
    EXECUTE IMMEDIATE p_sql INTO v_result;
    RETURN v_result;
EXCEPTION
    WHEN OTHERS THEN
        RETURN SQLERRM;
END execute_dynamic_sql;
/


select * from aispeech_results_json

--CONTAINS operator
select * from aispeech_results_json
    where contains ( jsondata, 'john' ) > 0

--Mixed Queries
select * from aispeech_results_json
    where amount < 100
    and   contains ( jsondata, 'smith' ) > 0

--An OR search
select * from aispeech_results_json
    where contains ( jsondata, 'john OR johnny' ) > 0

--Wildcards (% matches any string of characters, and an underscore _ character matches any single character)
select * from aispeech_results_json
  where contains ( jsondata, 'john%' ) > 0

--Phrase searches (an AND search similar to OR but implicit)
select * from aispeech_results_json
  where contains ( jsondata, 'first order' ) > 0

--Fuzzy searches (find not only the original search word, but also all those similar to it)
select * from aispeech_results_json
  where contains ( jsondata, 'fuzzy(popins)' ) > 0

--Near searches (words within specified distance of each other)
select * from aispeech_results_json
  where contains ( jsondata, 'near((order, smith), 1)' ) > 0

--Easy Text Search over Multiple Tables and Views with DBMS_SEARCH in 23c
--workshop: https://apexapps.oracle.com/pls/apex/r/dbpm/livelabs/view-workshop?wid=3721

--CREATE TABLE image_storage (
--    image_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--    image_name VARCHAR2(255),
--    image_data BLOB,
--    image_description VARCHAR2(1000),
--    uploaded_on DATE DEFAULT SYSDATE
--);

BEGIN
dbms_cloud.create_credential (
    credential_name => 'OCI_KEY_CRED',
    user_ocid => 'ocid1.user.oc1..[youruserocid]',
    tenancy_ocid => 'ocid1.tenancy.oc1..[yourtenancyocid]',
    private_key => '[yourprivatekey you can read this from file or put the contents of your pem without header, footer, and line wraps]'
    fingerprint => '[7f:yourfingerprint]'
);
END;