CREATE USER aiuser identified BY [Yourpassword];
grant CREATE session TO aiuser;
grant RESOURCE, db_developer_role TO aiuser;
grant unlimited tablespace TO aiuser;
grant EXECUTE ON javascript TO aiuser;
grant EXECUTE dynamic mle TO aiuser;
grant execute on DBMS_CLOUD to aiuser;
--switch to aiuser

--CREATE TABLE metering
--    (id RAW (16) NOT NULL,
--     date_loaded TIMESTAMP WITH TIME ZONE,
--     label varchar2(20),
--     jsondata CLOB
--     CONSTRAINT ensure_metering_json CHECK (jsondata IS JSON));
--
CREATE TABLE aivision_results
    (id RAW (16) NOT NULL,
     date_loaded TIMESTAMP WITH TIME ZONE,
     label varchar2(20),
     jsondata CLOB
     CONSTRAINT ensure_aivision_results_json CHECK (jsondata IS JSON));

--CREATE TABLE image_storage (
--    image_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--    image_name VARCHAR2(255),
--    image_data BLOB,
--    image_description VARCHAR2(1000),
--    uploaded_on DATE DEFAULT SYSDATE
--);

BEGIN
dbms_cloud.create_credential (
    credential_name => 'OCI_KEY_CRED',
    user_ocid => 'ocid1.user.oc1..[youruserocid]',
    tenancy_ocid => 'ocid1.tenancy.oc1..[yourtenancyocid]',
    private_key => '[yourprivatekey you can read this from file or put the contents of your pem without header, footer, and line wraps]'
    fingerprint => '[7f:yourfingerprint]'
);
END;