CREATE USER aiuser identified BY [Yourpassword];
grant CREATE session TO aiuser;
grant RESOURCE, db_developer_role TO aiuser;
grant unlimited tablespace TO aiuser;
grant EXECUTE ON javascript TO aiuser;
grant EXECUTE dynamic mle TO aiuser;
grant execute on DBMS_CLOUD to aiuser;
--switch to aiuser

--CREATE TABLE metering
--    (id RAW (16) NOT NULL,
--     date_loaded TIMESTAMP WITH TIME ZONE,
--     label varchar2(20),
--     jsondata CLOB
--     CONSTRAINT ensure_metering_json CHECK (jsondata IS JSON));
--
CREATE TABLE aivision_results
    (id RAW (16) NOT NULL,
     date_loaded TIMESTAMP WITH TIME ZONE,
     label varchar2(20),
     jsondata CLOB
     CONSTRAINT ensure_aivision_results_json CHECK (jsondata IS JSON));

create index airesultsindex on aivision_results(jsondata) indextype is ctxsys.context;

select index_name, index_type, status from user_indexes where index_name = 'AIRESULTSINDEX';
select idx_name, idx_table, idx_text_name from ctx_user_indexes;
select token_text from dr$airesultsindex$i;

select * from user_data

--CONTAINS operator
select * from user_data
    where contains ( jsondata, 'john' ) > 0

--Mixed Queries
select * from user_data
    where amount < 100
    and   contains ( jsondata, 'smith' ) > 0

--An OR search
select * from user_data
    where contains ( jsondata, 'john OR johnny' ) > 0

--Wildcards (% matches any string of characters, and an underscore _ character matches any single character)
select * from user_data
  where contains ( jsondata, 'john%' ) > 0

--Phrase searches (an AND search similar to OR but implicit)
select * from user_data
  where contains ( jsondata, 'first order' ) > 0

--Fuzzy searches (find not only the original search word, but also all those similar to it)
select * from user_data
  where contains ( jsondata, 'fuzzy(popins)' ) > 0

--Near searches (words within specified distance of each other)
select * from user_data
  where contains ( jsondata, 'near((order, smith), 1)' ) > 0

--Easy Text Search over Multiple Tables and Views with DBMS_SEARCH in 23c
--workshop: https://apexapps.oracle.com/pls/apex/r/dbpm/livelabs/view-workshop?wid=3721

--CREATE TABLE image_storage (
--    image_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
--    image_name VARCHAR2(255),
--    image_data BLOB,
--    image_description VARCHAR2(1000),
--    uploaded_on DATE DEFAULT SYSDATE
--);

BEGIN
dbms_cloud.create_credential (
    credential_name => 'OCI_KEY_CRED',
    user_ocid => 'ocid1.user.oc1..[youruserocid]',
    tenancy_ocid => 'ocid1.tenancy.oc1..[yourtenancyocid]',
    private_key => '[yourprivatekey you can read this from file or put the contents of your pem without header, footer, and line wraps]'
    fingerprint => '[7f:yourfingerprint]'
);
END;