set serveroutput on size unlimited

prompt [1/4] sc_inventory_risk_summary
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_inventory_risk_summary (
            product_id                    VARCHAR2(40) PRIMARY KEY
                REFERENCES sc_products (product_id),
            quarter_label                 VARCHAR2(30) NOT NULL,
            risk_level                    VARCHAR2(20) NOT NULL,
            stockout_probability          NUMBER(6,4) NOT NULL,
            at_risk_units                 NUMBER(12),
            projected_revenue_impact_usd  NUMBER(14,2),
            primary_region                VARCHAR2(100),
            recommendation_summary        VARCHAR2(4000),
            active_flag                   CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_inventory_risk_summary');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_inventory_risk_summary already exists');
    when others then
        dbms_output.put_line('FAIL: sc_inventory_risk_summary -> ' || sqlerrm);
        raise;
end;
/

prompt [2/4] sc_warehouse_geo
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_warehouse_geo (
            warehouse_id                  NUMBER PRIMARY KEY
                REFERENCES sc_warehouses (warehouse_id),
            warehouse_code                VARCHAR2(30) NOT NULL,
            county_name                   VARCHAR2(100) NOT NULL,
            state_code                    VARCHAR2(10) NOT NULL,
            region_name                   VARCHAR2(100) NOT NULL,
            latitude                      NUMBER(9,6) NOT NULL,
            longitude                     NUMBER(9,6) NOT NULL
        )
    ]';
    dbms_output.put_line('OK: created sc_warehouse_geo');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_warehouse_geo already exists');
    when others then
        dbms_output.put_line('FAIL: sc_warehouse_geo -> ' || sqlerrm);
        raise;
end;
/

prompt [3/4] sc_warehouse_risk_snapshot
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_warehouse_risk_snapshot (
            snapshot_id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id                    VARCHAR2(40) NOT NULL
                REFERENCES sc_products (product_id),
            warehouse_id                  NUMBER NOT NULL
                REFERENCES sc_warehouses (warehouse_id),
            hotspot_rank                  NUMBER(3) NOT NULL,
            hotspot_score                 NUMBER(6,4) NOT NULL,
            coverage_days                 NUMBER(6,2),
            backlog_units                 NUMBER(12),
            service_level_pct             NUMBER(5,2),
            at_risk_units                 NUMBER(12),
            revenue_impact_usd            NUMBER(14,2),
            risk_level                    VARCHAR2(20) NOT NULL,
            recommended_role              VARCHAR2(30) NOT NULL,
            active_flag                   CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_warehouse_risk_snapshot');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_warehouse_risk_snapshot already exists');
    when others then
        dbms_output.put_line('FAIL: sc_warehouse_risk_snapshot -> ' || sqlerrm);
        raise;
end;
/

prompt [4/4] sc_inventory_risk_demo_v
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE OR REPLACE VIEW sc_inventory_risk_demo_v AS
        SELECT
            summary.product_id,
            product.product_name,
            summary.quarter_label,
            summary.risk_level AS overall_risk_level,
            summary.stockout_probability,
            summary.at_risk_units AS product_at_risk_units,
            summary.projected_revenue_impact_usd,
            summary.primary_region,
            summary.recommendation_summary,
            warehouse.warehouse_id,
            warehouse.warehouse_name,
            geo.warehouse_code,
            geo.county_name,
            geo.state_code,
            geo.region_name,
            geo.latitude,
            geo.longitude,
            snapshot.hotspot_rank,
            snapshot.hotspot_score,
            snapshot.coverage_days,
            snapshot.backlog_units,
            snapshot.service_level_pct,
            snapshot.at_risk_units,
            snapshot.revenue_impact_usd,
            snapshot.risk_level,
            snapshot.recommended_role,
            summary.active_flag
        FROM sc_inventory_risk_summary summary
        JOIN sc_products product
          ON product.product_id = summary.product_id
        JOIN sc_warehouse_risk_snapshot snapshot
          ON snapshot.product_id = summary.product_id
         AND snapshot.active_flag = 'Y'
        JOIN sc_warehouses warehouse
          ON warehouse.warehouse_id = snapshot.warehouse_id
        JOIN sc_warehouse_geo geo
          ON geo.warehouse_id = snapshot.warehouse_id
        WHERE summary.active_flag = 'Y'
    ]';
    dbms_output.put_line('OK: created or replaced sc_inventory_risk_demo_v');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_inventory_risk_demo_v already exists');
    when others then
        dbms_output.put_line('FAIL: sc_inventory_risk_demo_v -> ' || sqlerrm);
        raise;
end;
/

prompt comments
comment on table sc_inventory_risk_summary is
    'Quarter-level product stockout risk summary used by the demo Select AI and inventory analysis agents.';
comment on column sc_inventory_risk_summary.stockout_probability is
    'Probability from 0 to 1 that the product will hit stockout conditions during the named quarter.';
comment on column sc_inventory_risk_summary.projected_revenue_impact_usd is
    'Estimated revenue impact in US dollars if no mitigation is taken.';
comment on column sc_inventory_risk_summary.primary_region is
    'Region currently driving the highest stockout pressure.';
comment on table sc_warehouse_geo is
    'Warehouse coordinates and region metadata used by the spatial hotspot renderer.';
comment on column sc_warehouse_geo.latitude is
    'Latitude in WGS84 decimal degrees.';
comment on column sc_warehouse_geo.longitude is
    'Longitude in WGS84 decimal degrees.';
comment on table sc_warehouse_risk_snapshot is
    'Per-product warehouse hotspot detail used for maps, region drill-down, and action recommendations.';
comment on column sc_warehouse_risk_snapshot.recommended_role is
    'How the warehouse should be treated in an action plan, such as DESTINATION_HOTSPOT, SOURCE_BUFFER, or RELAY_NODE.';
comment on table sc_inventory_risk_demo_v is
    'Flattened view that combines product risk, warehouse hotspot metrics, and warehouse geography for Select AI prompts.';
