set serveroutput on size unlimited

prompt [1/12] sc_suppliers
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_suppliers (
            supplier_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_name       VARCHAR2(200) NOT NULL,
            tier_level          NUMBER(2) DEFAULT 1 NOT NULL,
            region_code         VARCHAR2(100) NOT NULL,
            on_time_pct         NUMBER(5,2),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_suppliers');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_suppliers already exists');
    when others then
        dbms_output.put_line('FAIL: sc_suppliers -> ' || sqlerrm);
        raise;
end;
/

prompt [2/12] sc_plants
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_plants (
            plant_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plant_name          VARCHAR2(200) NOT NULL,
            cycle_days          NUMBER(6,2),
            utilization_pct     NUMBER(5,2),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_plants');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_plants already exists');
    when others then
        dbms_output.put_line('FAIL: sc_plants -> ' || sqlerrm);
        raise;
end;
/

prompt [3/12] sc_ports
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_ports (
            port_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            port_name           VARCHAR2(200) NOT NULL,
            eta_hours           NUMBER(8),
            delay_risk_score    NUMBER(6,4),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_ports');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_ports already exists');
    when others then
        dbms_output.put_line('FAIL: sc_ports -> ' || sqlerrm);
        raise;
end;
/

prompt [4/12] sc_warehouses
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_warehouses (
            warehouse_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            warehouse_name      VARCHAR2(200) NOT NULL,
            inventory_units     NUMBER(12),
            fill_rate_pct       NUMBER(5,2),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_warehouses');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_warehouses already exists');
    when others then
        dbms_output.put_line('FAIL: sc_warehouses -> ' || sqlerrm);
        raise;
end;
/

prompt [5/12] sc_products
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_products (
            product_id          VARCHAR2(40) PRIMARY KEY,
            product_name        VARCHAR2(200) NOT NULL,
            demand_change_pct   NUMBER(6,2),
            margin_pct          NUMBER(5,2),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_products');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_products already exists');
    when others then
        dbms_output.put_line('FAIL: sc_products -> ' || sqlerrm);
        raise;
end;
/

prompt [6/12] sc_alerts
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_alerts (
            alert_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            alert_name          VARCHAR2(200) NOT NULL,
            lane_name           VARCHAR2(100),
            risk_score          NUMBER(6,4),
            active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (active_flag IN ('Y', 'N'))
        )
    ]';
    dbms_output.put_line('OK: created sc_alerts');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_alerts already exists');
    when others then
        dbms_output.put_line('FAIL: sc_alerts -> ' || sqlerrm);
        raise;
end;
/

prompt [7/12] sc_supplier_plant
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_supplier_plant (
            supplier_plant_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_id         NUMBER NOT NULL REFERENCES sc_suppliers (supplier_id),
            plant_id            NUMBER NOT NULL REFERENCES sc_plants (plant_id),
            relationship_label  VARCHAR2(30) DEFAULT 'SUPPLIES' NOT NULL,
            is_current          CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (is_current IN ('Y', 'N')),
            effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
            effective_end_dt    DATE
        )
    ]';
    dbms_output.put_line('OK: created sc_supplier_plant');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_supplier_plant already exists');
    when others then
        dbms_output.put_line('FAIL: sc_supplier_plant -> ' || sqlerrm);
        raise;
end;
/

prompt [8/12] sc_plant_port
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_plant_port (
            plant_port_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plant_id            NUMBER NOT NULL REFERENCES sc_plants (plant_id),
            port_id             NUMBER NOT NULL REFERENCES sc_ports (port_id),
            relationship_label  VARCHAR2(30) DEFAULT 'SHIPS_VIA' NOT NULL,
            is_current          CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (is_current IN ('Y', 'N')),
            effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
            effective_end_dt    DATE
        )
    ]';
    dbms_output.put_line('OK: created sc_plant_port');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_plant_port already exists');
    when others then
        dbms_output.put_line('FAIL: sc_plant_port -> ' || sqlerrm);
        raise;
end;
/

prompt [9/12] sc_port_warehouse
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_port_warehouse (
            port_warehouse_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            port_id             NUMBER NOT NULL REFERENCES sc_ports (port_id),
            warehouse_id        NUMBER NOT NULL REFERENCES sc_warehouses (warehouse_id),
            relationship_label  VARCHAR2(30) DEFAULT 'ROUTES_TO' NOT NULL,
            is_current          CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (is_current IN ('Y', 'N')),
            effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
            effective_end_dt    DATE
        )
    ]';
    dbms_output.put_line('OK: created sc_port_warehouse');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_port_warehouse already exists');
    when others then
        dbms_output.put_line('FAIL: sc_port_warehouse -> ' || sqlerrm);
        raise;
end;
/

prompt [10/12] sc_warehouse_product
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_warehouse_product (
            warehouse_product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            warehouse_id         NUMBER NOT NULL REFERENCES sc_warehouses (warehouse_id),
            product_id           VARCHAR2(40) NOT NULL REFERENCES sc_products (product_id),
            relationship_label   VARCHAR2(30) DEFAULT 'STOCKS' NOT NULL,
            is_current           CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (is_current IN ('Y', 'N')),
            effective_start_dt   DATE DEFAULT SYSDATE NOT NULL,
            effective_end_dt     DATE
        )
    ]';
    dbms_output.put_line('OK: created sc_warehouse_product');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_warehouse_product already exists');
    when others then
        dbms_output.put_line('FAIL: sc_warehouse_product -> ' || sqlerrm);
        raise;
end;
/

prompt [11/12] sc_alert_port
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE TABLE sc_alert_port (
            alert_port_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            alert_id            NUMBER NOT NULL REFERENCES sc_alerts (alert_id),
            port_id             NUMBER NOT NULL REFERENCES sc_ports (port_id),
            relationship_label  VARCHAR2(30) DEFAULT 'AFFECTS' NOT NULL,
            is_current          CHAR(1) DEFAULT 'Y' NOT NULL
                CHECK (is_current IN ('Y', 'N')),
            effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
            effective_end_dt    DATE
        )
    ]';
    dbms_output.put_line('OK: created sc_alert_port');
exception
    when object_exists then
        dbms_output.put_line('SKIP: sc_alert_port already exists');
    when others then
        dbms_output.put_line('FAIL: sc_alert_port -> ' || sqlerrm);
        raise;
end;
/

prompt [12/12] supply_chain_graph
declare
    object_exists exception;
    pragma exception_init(object_exists, -955);
begin
    execute immediate q'[
        CREATE PROPERTY GRAPH supply_chain_graph
            VERTEX TABLES (
                sc_suppliers AS suppliers
                    KEY (supplier_id)
                    LABEL supplier
                    PROPERTIES (
                        supplier_id,
                        supplier_name,
                        tier_level,
                        region_code,
                        on_time_pct,
                        active_flag
                    ),
                sc_plants AS plants
                    KEY (plant_id)
                    LABEL plant
                    PROPERTIES (
                        plant_id,
                        plant_name,
                        cycle_days,
                        utilization_pct,
                        active_flag
                    ),
                sc_ports AS ports
                    KEY (port_id)
                    LABEL port
                    PROPERTIES (
                        port_id,
                        port_name,
                        eta_hours,
                        delay_risk_score,
                        active_flag
                    ),
                sc_warehouses AS warehouses
                    KEY (warehouse_id)
                    LABEL warehouse
                    PROPERTIES (
                        warehouse_id,
                        warehouse_name,
                        inventory_units,
                        fill_rate_pct,
                        active_flag
                    ),
                sc_products AS products
                    KEY (product_id)
                    LABEL product
                    PROPERTIES (
                        product_id,
                        product_name,
                        demand_change_pct,
                        margin_pct,
                        active_flag
                    ),
                sc_alerts AS alerts
                    KEY (alert_id)
                    LABEL alert
                    PROPERTIES (
                        alert_id,
                        alert_name,
                        lane_name,
                        risk_score,
                        active_flag
                    )
            )
            EDGE TABLES (
                sc_supplier_plant AS supplies
                    KEY (supplier_plant_id)
                    SOURCE KEY (supplier_id) REFERENCES suppliers (supplier_id)
                    DESTINATION KEY (plant_id) REFERENCES plants (plant_id)
                    LABEL supplies
                    PROPERTIES (
                        relationship_label,
                        is_current,
                        effective_start_dt,
                        effective_end_dt
                    ),
                sc_plant_port AS ships_via
                    KEY (plant_port_id)
                    SOURCE KEY (plant_id) REFERENCES plants (plant_id)
                    DESTINATION KEY (port_id) REFERENCES ports (port_id)
                    LABEL ships_via
                    PROPERTIES (
                        relationship_label,
                        is_current,
                        effective_start_dt,
                        effective_end_dt
                    ),
                sc_port_warehouse AS routes_to
                    KEY (port_warehouse_id)
                    SOURCE KEY (port_id) REFERENCES ports (port_id)
                    DESTINATION KEY (warehouse_id) REFERENCES warehouses (warehouse_id)
                    LABEL routes_to
                    PROPERTIES (
                        relationship_label,
                        is_current,
                        effective_start_dt,
                        effective_end_dt
                    ),
                sc_warehouse_product AS stocks
                    KEY (warehouse_product_id)
                    SOURCE KEY (warehouse_id) REFERENCES warehouses (warehouse_id)
                    DESTINATION KEY (product_id) REFERENCES products (product_id)
                    LABEL stocks
                    PROPERTIES (
                        relationship_label,
                        is_current,
                        effective_start_dt,
                        effective_end_dt
                    ),
                sc_alert_port AS affects
                    KEY (alert_port_id)
                    SOURCE KEY (alert_id) REFERENCES alerts (alert_id)
                    DESTINATION KEY (port_id) REFERENCES ports (port_id)
                    LABEL affects
                    PROPERTIES (
                        relationship_label,
                        is_current,
                        effective_start_dt,
                        effective_end_dt
                    )
            )
            OPTIONS (TRUSTED MODE)
    ]';
    dbms_output.put_line('OK: created supply_chain_graph');
exception
    when object_exists then
        dbms_output.put_line('SKIP: supply_chain_graph already exists');
    when others then
        dbms_output.put_line('FAIL: supply_chain_graph -> ' || sqlerrm);
        raise;
end;
/
