-- supply_chain_graph_model.sql
--
-- Purpose
--   Show a plausible Oracle Database schema and query shape behind the
--   Java graph agent's current demo PNG.
--
-- Graph shape rendered today
--   SUPPLIER -> PLANT -> PORT -> WAREHOUSE -> PRODUCT
--                        ^
--                        |
--                      ALERT
--
-- The Java agent currently returns seeded sample values in GraphTools.
-- This file shows how the same shape could come from Oracle Database
-- tables plus an Oracle Property Graph query.

------------------------------------------------------------------------
-- 1. Relational tables
------------------------------------------------------------------------

CREATE TABLE sc_suppliers (
    supplier_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name       VARCHAR2(200) NOT NULL,
    tier_level          NUMBER(2) DEFAULT 1 NOT NULL,
    region_code         VARCHAR2(100) NOT NULL,
    on_time_pct         NUMBER(5,2),
    active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE sc_plants (
    plant_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_name          VARCHAR2(200) NOT NULL,
    cycle_days          NUMBER(6,2),
    utilization_pct     NUMBER(5,2),
    active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE sc_ports (
    port_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    port_name           VARCHAR2(200) NOT NULL,
    eta_hours           NUMBER(8),
    delay_risk_score    NUMBER(6,4),
    active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE sc_warehouses (
    warehouse_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name      VARCHAR2(200) NOT NULL,
    inventory_units     NUMBER(12),
    fill_rate_pct       NUMBER(5,2),
    active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE sc_products (
    product_id          VARCHAR2(40) PRIMARY KEY,
    product_name        VARCHAR2(200) NOT NULL,
    demand_change_pct   NUMBER(6,2),
    margin_pct          NUMBER(5,2),
    active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE sc_alerts (
    alert_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_name          VARCHAR2(200) NOT NULL,
    lane_name           VARCHAR2(100),
    risk_score          NUMBER(6,4),
    active_flag         CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (active_flag IN ('Y', 'N'))
);

-- Edge tables mirror the relationships the renderer draws.

CREATE TABLE sc_supplier_plant (
    supplier_plant_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         NUMBER NOT NULL REFERENCES sc_suppliers (supplier_id),
    plant_id            NUMBER NOT NULL REFERENCES sc_plants (plant_id),
    relationship_label  VARCHAR2(30) DEFAULT 'SUPPLIES' NOT NULL,
    is_current          CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (is_current IN ('Y', 'N')),
    effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
    effective_end_dt    DATE
);

CREATE TABLE sc_plant_port (
    plant_port_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id            NUMBER NOT NULL REFERENCES sc_plants (plant_id),
    port_id             NUMBER NOT NULL REFERENCES sc_ports (port_id),
    relationship_label  VARCHAR2(30) DEFAULT 'SHIPS_VIA' NOT NULL,
    is_current          CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (is_current IN ('Y', 'N')),
    effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
    effective_end_dt    DATE
);

CREATE TABLE sc_port_warehouse (
    port_warehouse_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    port_id             NUMBER NOT NULL REFERENCES sc_ports (port_id),
    warehouse_id        NUMBER NOT NULL REFERENCES sc_warehouses (warehouse_id),
    relationship_label  VARCHAR2(30) DEFAULT 'ROUTES_TO' NOT NULL,
    is_current          CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (is_current IN ('Y', 'N')),
    effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
    effective_end_dt    DATE
);

CREATE TABLE sc_warehouse_product (
    warehouse_product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id         NUMBER NOT NULL REFERENCES sc_warehouses (warehouse_id),
    product_id           VARCHAR2(40) NOT NULL REFERENCES sc_products (product_id),
    relationship_label   VARCHAR2(30) DEFAULT 'STOCKS' NOT NULL,
    is_current           CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (is_current IN ('Y', 'N')),
    effective_start_dt   DATE DEFAULT SYSDATE NOT NULL,
    effective_end_dt     DATE
);

CREATE TABLE sc_alert_port (
    alert_port_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id            NUMBER NOT NULL REFERENCES sc_alerts (alert_id),
    port_id             NUMBER NOT NULL REFERENCES sc_ports (port_id),
    relationship_label  VARCHAR2(30) DEFAULT 'AFFECTS' NOT NULL,
    is_current          CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (is_current IN ('Y', 'N')),
    effective_start_dt  DATE DEFAULT SYSDATE NOT NULL,
    effective_end_dt    DATE
);

------------------------------------------------------------------------
-- 2. Property graph definition
------------------------------------------------------------------------
--
-- This exposes the same relational rows as graph vertices and edges.
-- Labels are chosen to line up with the Java renderer's node and edge types.

CREATE PROPERTY GRAPH supply_chain_graph
    VERTEX TABLES (
        sc_suppliers AS suppliers
            KEY (supplier_id)
            LABEL supplier
            PROPERTIES (
                supplier_id,
                supplier_name,
                tier_level,
                region_code,
                on_time_pct,
                active_flag
            ),
        sc_plants AS plants
            KEY (plant_id)
            LABEL plant
            PROPERTIES (
                plant_id,
                plant_name,
                cycle_days,
                utilization_pct,
                active_flag
            ),
        sc_ports AS ports
            KEY (port_id)
            LABEL port
            PROPERTIES (
                port_id,
                port_name,
                eta_hours,
                delay_risk_score,
                active_flag
            ),
        sc_warehouses AS warehouses
            KEY (warehouse_id)
            LABEL warehouse
            PROPERTIES (
                warehouse_id,
                warehouse_name,
                inventory_units,
                fill_rate_pct,
                active_flag
            ),
        sc_products AS products
            KEY (product_id)
            LABEL product
            PROPERTIES (
                product_id,
                product_name,
                demand_change_pct,
                margin_pct,
                active_flag
            ),
        sc_alerts AS alerts
            KEY (alert_id)
            LABEL alert
            PROPERTIES (
                alert_id,
                alert_name,
                lane_name,
                risk_score,
                active_flag
            )
    )
    EDGE TABLES (
        sc_supplier_plant AS supplies
            KEY (supplier_plant_id)
            SOURCE KEY (supplier_id) REFERENCES suppliers (supplier_id)
            DESTINATION KEY (plant_id) REFERENCES plants (plant_id)
            LABEL supplies
            PROPERTIES (
                relationship_label,
                is_current,
                effective_start_dt,
                effective_end_dt
            ),
        sc_plant_port AS ships_via
            KEY (plant_port_id)
            SOURCE KEY (plant_id) REFERENCES plants (plant_id)
            DESTINATION KEY (port_id) REFERENCES ports (port_id)
            LABEL ships_via
            PROPERTIES (
                relationship_label,
                is_current,
                effective_start_dt,
                effective_end_dt
            ),
        sc_port_warehouse AS routes_to
            KEY (port_warehouse_id)
            SOURCE KEY (port_id) REFERENCES ports (port_id)
            DESTINATION KEY (warehouse_id) REFERENCES warehouses (warehouse_id)
            LABEL routes_to
            PROPERTIES (
                relationship_label,
                is_current,
                effective_start_dt,
                effective_end_dt
            ),
        sc_warehouse_product AS stocks
            KEY (warehouse_product_id)
            SOURCE KEY (warehouse_id) REFERENCES warehouses (warehouse_id)
            DESTINATION KEY (product_id) REFERENCES products (product_id)
            LABEL stocks
            PROPERTIES (
                relationship_label,
                is_current,
                effective_start_dt,
                effective_end_dt
            ),
        sc_alert_port AS affects
            KEY (alert_port_id)
            SOURCE KEY (alert_id) REFERENCES alerts (alert_id)
            DESTINATION KEY (port_id) REFERENCES ports (port_id)
            LABEL affects
            PROPERTIES (
                relationship_label,
                is_current,
                effective_start_dt,
                effective_end_dt
            )
    )
    OPTIONS (TRUSTED MODE);

------------------------------------------------------------------------
-- 3. Query pattern the agent would use
------------------------------------------------------------------------
--
-- Why this query shape works:
--   1. GRAPH_TABLE finds the product dependency path.
--   2. A regular SQL join brings in an active alert for the matched port.
--   3. The final SELECT emits the fields the Java agent currently renders.
--
-- Note:
--   GRAPH_TABLE is great for the main path traversal. For optional enrichments,
--   it is often simpler to join the graph result back to relational tables.

VAR product_id VARCHAR2(40);
EXEC :product_id := 'SKU-500';

WITH dependency_path AS (
    SELECT
        supplier_id,
        supplier_name,
        tier_level,
        supplier_region,
        on_time_pct,
        plant_id,
        plant_name,
        cycle_days,
        utilization_pct,
        port_id,
        port_name,
        eta_hours,
        delay_risk_score,
        warehouse_id,
        warehouse_name,
        inventory_units,
        fill_rate_pct,
        product_id,
        product_name,
        demand_change_pct,
        margin_pct
    FROM GRAPH_TABLE (
        supply_chain_graph
        MATCH
            (s IS supplier) -[e1 IS supplies]-> (p IS plant)
                            -[e2 IS ships_via]-> (po IS port)
                            -[e3 IS routes_to]-> (w IS warehouse)
                            -[e4 IS stocks]-> (pr IS product)
        WHERE pr.product_id = :product_id
          AND s.active_flag = 'Y'
          AND p.active_flag = 'Y'
          AND po.active_flag = 'Y'
          AND w.active_flag = 'Y'
          AND pr.active_flag = 'Y'
          AND e1.is_current = 'Y'
          AND e2.is_current = 'Y'
          AND e3.is_current = 'Y'
          AND e4.is_current = 'Y'
        COLUMNS (
            s.supplier_id AS supplier_id,
            s.supplier_name AS supplier_name,
            s.tier_level AS tier_level,
            s.region_code AS supplier_region,
            s.on_time_pct AS on_time_pct,
            p.plant_id AS plant_id,
            p.plant_name AS plant_name,
            p.cycle_days AS cycle_days,
            p.utilization_pct AS utilization_pct,
            po.port_id AS port_id,
            po.port_name AS port_name,
            po.eta_hours AS eta_hours,
            po.delay_risk_score AS delay_risk_score,
            w.warehouse_id AS warehouse_id,
            w.warehouse_name AS warehouse_name,
            w.inventory_units AS inventory_units,
            w.fill_rate_pct AS fill_rate_pct,
            pr.product_id AS product_id,
            pr.product_name AS product_name,
            pr.demand_change_pct AS demand_change_pct,
            pr.margin_pct AS margin_pct
        )
    )
),
active_alert AS (
    SELECT
        ap.port_id,
        a.alert_id,
        a.alert_name,
        a.lane_name,
        a.risk_score
    FROM sc_alert_port ap
    JOIN sc_alerts a
      ON a.alert_id = ap.alert_id
    WHERE ap.is_current = 'Y'
      AND a.active_flag = 'Y'
)
SELECT
    dp.product_id,
    dp.product_name,
    dp.supplier_name,
    dp.tier_level,
    dp.supplier_region,
    dp.on_time_pct,
    dp.plant_name,
    dp.cycle_days,
    dp.utilization_pct,
    dp.port_name,
    dp.eta_hours,
    dp.delay_risk_score,
    dp.warehouse_name,
    dp.inventory_units,
    dp.fill_rate_pct,
    dp.demand_change_pct,
    dp.margin_pct,
    aa.alert_name,
    aa.lane_name,
    aa.risk_score AS alert_risk
FROM dependency_path dp
LEFT JOIN active_alert aa
  ON aa.port_id = dp.port_id;

------------------------------------------------------------------------
-- 4. Query pattern for the exact Java payload shape
------------------------------------------------------------------------
--
-- This turns the path query into the same node/edge payload structure that
-- GraphTools.GraphResponse returns today.

WITH graph_row AS (
    WITH dependency_path AS (
        SELECT
            supplier_name,
            tier_level,
            supplier_region,
            on_time_pct,
            plant_name,
            cycle_days,
            utilization_pct,
            port_id,
            port_name,
            eta_hours,
            delay_risk_score,
            warehouse_name,
            inventory_units,
            fill_rate_pct,
            product_id,
            demand_change_pct,
            margin_pct
        FROM GRAPH_TABLE (
            supply_chain_graph
            MATCH
                (s IS supplier) -[e1 IS supplies]-> (p IS plant)
                                -[e2 IS ships_via]-> (po IS port)
                                -[e3 IS routes_to]-> (w IS warehouse)
                                -[e4 IS stocks]-> (pr IS product)
            WHERE pr.product_id = :product_id
              AND e1.is_current = 'Y'
              AND e2.is_current = 'Y'
              AND e3.is_current = 'Y'
              AND e4.is_current = 'Y'
            COLUMNS (
                s.supplier_name AS supplier_name,
                s.tier_level AS tier_level,
                s.region_code AS supplier_region,
                s.on_time_pct AS on_time_pct,
                p.plant_name AS plant_name,
                p.cycle_days AS cycle_days,
                p.utilization_pct AS utilization_pct,
                po.port_id AS port_id,
                po.port_name AS port_name,
                po.eta_hours AS eta_hours,
                po.delay_risk_score AS delay_risk_score,
                w.warehouse_name AS warehouse_name,
                w.inventory_units AS inventory_units,
                w.fill_rate_pct AS fill_rate_pct,
                pr.product_id AS product_id,
                pr.demand_change_pct AS demand_change_pct,
                pr.margin_pct AS margin_pct
            )
        )
    )
    SELECT
        dp.*,
        a.alert_name,
        a.lane_name,
        a.risk_score AS alert_risk
    FROM dependency_path dp
    LEFT JOIN sc_alert_port ap
      ON ap.port_id = dp.port_id
     AND ap.is_current = 'Y'
    LEFT JOIN sc_alerts a
      ON a.alert_id = ap.alert_id
     AND a.active_flag = 'Y'
),
node_rows AS (
    SELECT 1 AS sort_order,
           'supplier' AS id,
           'Supplier: ' || supplier_name AS label,
           'SUPPLIER' AS type,
           'Tier ' || tier_level || ' | ' || supplier_region AS detail,
           'On-time ' || TO_CHAR(on_time_pct, 'FM990D00') || '%' AS metric
    FROM graph_row
    UNION ALL
    SELECT 2,
           'plant',
           'Plant: ' || plant_name,
           'PLANT',
           'Cycle ' || TO_CHAR(cycle_days, 'FM990D0') || ' days',
           'Utilization ' || TO_CHAR(utilization_pct, 'FM990D00') || '%'
    FROM graph_row
    UNION ALL
    SELECT 3,
           'port',
           'Port: ' || port_name,
           'PORT',
           'ETA ' || TO_CHAR(eta_hours) || ' hrs',
           'Delay risk ' || TO_CHAR(delay_risk_score, 'FM0D00')
    FROM graph_row
    UNION ALL
    SELECT 4,
           'warehouse',
           'Warehouse: ' || warehouse_name,
           'WAREHOUSE',
           'Inventory ' || TO_CHAR(inventory_units) || ' units',
           'Fill rate ' || TO_CHAR(fill_rate_pct, 'FM990D00') || '%'
    FROM graph_row
    UNION ALL
    SELECT 5,
           'product',
           'Product: ' || product_id,
           'PRODUCT',
           'Demand ' || CASE WHEN demand_change_pct >= 0 THEN '+' END
               || TO_CHAR(demand_change_pct, 'FM990D00') || '%',
           'Margin ' || TO_CHAR(margin_pct, 'FM990D00') || '%'
    FROM graph_row
    UNION ALL
    SELECT 6,
           'alert',
           'Alert: ' || NVL(alert_name, 'No Active Alert'),
           'ALERT',
           NVL(lane_name, 'No active lane'),
           'Risk ' || TO_CHAR(NVL(alert_risk, 0), 'FM0D00')
    FROM graph_row
),
edge_rows AS (
    SELECT 1 AS sort_order, 'supplier' AS from_id, 'plant' AS to_id, 'SUPPLIES' AS label FROM dual
    UNION ALL
    SELECT 2, 'plant', 'port', 'SHIPS_VIA' FROM dual
    UNION ALL
    SELECT 3, 'port', 'warehouse', 'ROUTES_TO' FROM dual
    UNION ALL
    SELECT 4, 'warehouse', 'product', 'STOCKS' FROM dual
    UNION ALL
    SELECT 5, 'alert', 'port', 'AFFECTS' FROM dual
)
SELECT JSON_OBJECT(
           'nodes' VALUE (
               SELECT JSON_ARRAYAGG(
                          JSON_OBJECT(
                              'id' VALUE id,
                              'label' VALUE label,
                              'type' VALUE type,
                              'detail' VALUE detail,
                              'metric' VALUE metric
                          )
                          ORDER BY sort_order
                          RETURNING CLOB
                      )
               FROM node_rows
           ),
           'edges' VALUE (
               SELECT JSON_ARRAYAGG(
                          JSON_OBJECT(
                              'from' VALUE from_id,
                              'to' VALUE to_id,
                              'label' VALUE label
                          )
                          ORDER BY sort_order
                          RETURNING CLOB
                      )
               FROM edge_rows
           )
           RETURNING CLOB
       ) AS graph_payload
FROM dual;

------------------------------------------------------------------------
-- 5. How this maps back into the Java agent
------------------------------------------------------------------------
--
-- GraphTools can stop generating random values and instead:
--   1. bind :product_id from GraphRequest.productId()
--   2. run the query above with JDBC
--   3. deserialize graph_payload into:
--        GraphResponse(List<Map<String, String>> nodes,
--                      List<Map<String, String>> edges)
--   4. pass that GraphResponse into GraphA2AConfiguration.renderGraphPng(...)
